version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  sync:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run: go run cmd/pagerduty-slack-sync/main.go
      - go/save-cache

workflows:
  version: 2
  commit:
    jobs:
      - sync
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - sync